import Foundation

/// A lightweight client that reports app activity events to a Kyome Analytics server.
public actor KyomeAnalyticsClient {
    private let configuration: KyomeAnalyticsConfiguration
    private let installationStore: any InstallationStore
    private let transport: any AnalyticsTransport
    private let calendar: Calendar

    /// Creates a client with explicit dependencies.
    ///
    /// Use this initializer when you want to provide a custom installation store,
    /// transport, or calendar, such as in tests.
    ///
    /// - Parameters:
    ///   - configuration: The server endpoint, app key, and application identifier.
    ///   - installationStore: The store used to persist the install ID and last successful send day.
    ///   - transport: The transport used to send events to the server.
    ///   - calendar: The calendar used to determine whether an event has already been sent for the current day. Defaults to Gregorian UTC.
    public init(
        configuration: KyomeAnalyticsConfiguration,
        installationStore: (any InstallationStore)? = nil,
        transport: (any AnalyticsTransport)? = nil,
        calendar: Calendar? = nil
    ) {
        self.configuration = configuration
        self.installationStore = installationStore ?? FileInstallationStore(applicationIdentifier: configuration.applicationIdentifier)
        self.transport = transport ?? URLSessionAnalyticsTransport()
        self.calendar = calendar ?? Self.defaultCalendar
    }

    /// Creates a client for the default Kyome Analytics endpoint.
    ///
    /// - Parameters:
    ///   - appKey: The public app key generated by the analytics server.
    ///   - applicationIdentifier: The app identifier used for local state storage. Defaults to the main bundle identifier.
    ///   - isEnabled: A Boolean value that controls whether events are sent. Defaults to `true`.
    public init(appKey: String, applicationIdentifier: String? = nil, isEnabled: Bool = true) {
        self.init(configuration: KyomeAnalyticsConfiguration(appKey: appKey, applicationIdentifier: applicationIdentifier, isEnabled: isEnabled))
    }

    /// Creates a client using a custom event endpoint.
    ///
    /// Use this initializer for local development, staging, or self-hosted testing.
    ///
    /// - Parameters:
    ///   - endpoint: The full event endpoint URL, usually ending in `/api/v1/events`.
    ///   - appKey: The public app key generated by the analytics server.
    ///   - applicationIdentifier: The app identifier used for local state storage. Defaults to the main bundle identifier.
    ///   - isEnabled: A Boolean value that controls whether events are sent. Defaults to `true`.
    public init(endpoint: URL, appKey: String, applicationIdentifier: String? = nil, isEnabled: Bool = true) {
        self.init(configuration: KyomeAnalyticsConfiguration(endpoint: endpoint, appKey: appKey, applicationIdentifier: applicationIdentifier, isEnabled: isEnabled))
    }

    /// Sends an app activity event if one has not already been sent for the current UTC day.
    ///
    /// The method returns `false` without touching local state or making a network
    /// request when analytics are disabled. It also returns `false` without making
    /// a network request when the stored last successful send day matches `now`.
    ///
    /// - Parameters:
    ///   - appVersion: The app version to report. Defaults to `CFBundleShortVersionString`.
    ///   - build: The build number to report. Defaults to `CFBundleVersion`.
    ///   - now: The timestamp used for the event and daily send check.
    /// - Returns: `true` when an event was sent, or `false` when today's event had already been sent.
    /// - Throws: Any error raised while reading local state, sending the request, or saving the successful send day.
    @discardableResult
    public func trackActiveApp(
        appVersion: String? = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String,
        build: String? = Bundle.main.infoDictionary?["CFBundleVersion"] as? String,
        now: Date = Date()
    ) async throws -> Bool {
        guard configuration.isEnabled else {
            return false
        }

        let day = calendar.startOfDay(for: now)
        if try installationStore.lastSentDay() == day {
            return false
        }

        let event = try ActiveAppEvent(
            installID: installationStore.installID(),
            appVersion: appVersion,
            build: build,
            sentAt: now
        )
        try await transport.send(event: event, configuration: configuration)
        try installationStore.setLastSentDay(day)
        return true
    }
}

private extension KyomeAnalyticsClient {
    static let defaultCalendar: Calendar = {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        return calendar
    }()
}
