import Foundation

/// Configuration values required to send analytics events.
public struct KyomeAnalyticsConfiguration: Sendable {
    /// The default Kyome Analytics event endpoint.
    public static let defaultEndpoint = URL(string: "https://analytics.kyome.io/api/v1/events")!

    /// The full event endpoint URL, usually ending in `/api/v1/events`.
    public let endpoint: URL

    /// The public app key generated by the analytics server.
    public let appKey: String

    /// The identifier used to separate local analytics state for this app.
    public let applicationIdentifier: String

    /// A Boolean value that controls whether the client sends analytics events.
    public let isEnabled: Bool

    /// Creates analytics configuration.
    ///
    /// - Parameters:
    ///   - endpoint: The full event endpoint URL. Defaults to ``defaultEndpoint``.
    ///   - appKey: The public app key generated by the analytics server.
    ///   - applicationIdentifier: The identifier used for local state storage. Defaults to the main bundle identifier.
    ///   - isEnabled: A Boolean value that controls whether events are sent. Defaults to `true`.
    public init(endpoint: URL = Self.defaultEndpoint, appKey: String, applicationIdentifier: String? = nil, isEnabled: Bool = true) {
        self.endpoint = endpoint
        self.appKey = appKey
        self.applicationIdentifier = applicationIdentifier ?? Bundle.main.bundleIdentifier ?? "unknown"
        self.isEnabled = isEnabled
    }
}
